services:
  - type: web
    name: breast-cancer-classification
    runtime: image
    image:
      url: ghcr.io/amarasie0602/breast-cancer-classification:latest
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: CHECKPOINT_PATH
        value: checkpoints/best_mag40.pt
