"""Point the Hugging Face Space at a published serving image.

The Space holds no code of its own: its Dockerfile is a single FROM line
naming an image CD has already built and pushed to GHCR. Pinning that line
to the commit's tag (rather than :latest) means every deploy is a new Space
commit, so the Space rebuilds, and the running app can be traced back to the
exact commit it came from.

Run by the CD workflow after the image is pushed:

    HF_TOKEN=... python -m scripts.deploy_space --space user/name --image ghcr.io/...:<sha>
"""

import argparse
import os
import shutil
import tempfile
from pathlib import Path
from typing import Union

SPACE_SOURCE_DIR = Path(__file__).resolve().parent.parent / "deploy" / "huggingface"


def render_space_files(image: str, out_dir: Union[str, Path]) -> None:
    """Write the Space's README (card + metadata) and a Dockerfile built on ``image``."""
    if ":" not in image.rsplit("/", 1)[-1]:
        raise ValueError(f"image {image!r} has no tag; deploy a pinned tag, not an implicit :latest")
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(SPACE_SOURCE_DIR / "README.md", out_dir / "README.md")
    (out_dir / "Dockerfile").write_text(
        "# Generated by scripts/deploy_space.py on each deploy; edits here are overwritten.\n"
        f"FROM {image}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--space", required=True, help="e.g. username/breast-cancer-classification")
    parser.add_argument("--image", required=True, help="fully tagged image reference")
    args = parser.parse_args()

    # Only CD needs this, so it isn't in the serving or training requirements.
    from huggingface_hub import HfApi

    api = HfApi(token=os.environ["HF_TOKEN"])
    api.create_repo(args.space, repo_type="space", space_sdk="docker", exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        render_space_files(args.image, tmp)
        api.upload_folder(
            repo_id=args.space,
            repo_type="space",
            folder_path=tmp,
            commit_message=f"Deploy {args.image.rsplit(':', 1)[-1][:7]}",
        )
    print(f"Deployed {args.image} to https://huggingface.co/spaces/{args.space}")


if __name__ == "__main__":
    main()
